### ISSUE TITLE
MsgHeader Encode 时没有区分版本号

### ISSUE THREAD

**Issue by deferclose** [fakeyanss/jt808-server-go#11]
2019版本的消息头中有协议版本号，之前的版本没有，但MsgHeader Encode时没有区分收到的消息版本

**Comment by fakeyanss** [comment]
> 2019版本的消息头中有协议版本号，之前的版本没有，但MsgHeader Encode时没有区分收到的消息版本

是的，我在开发分支修复这个问题了，最近会合入到主分支。

**Comment by fakeyanss** [comment]
感觉媒体分支会开发的比较慢，先把这一块encode的修复单独合入主分支了。
#12
