### ISSUE TITLE
Failed to serve session | error="Fail to find device cache

### ISSUE THREAD

**Issue by zhangpengkai** [fakeyanss/jt808-server-go#16]
为什么一直鉴权失败呢  收到的消息ID一直是0102

**Comment by fakeyanss** [comment]
贴一下jt808-server的日志，把收到的终端消息和回复贴出来。

**Comment by supawei** [comment]
![image](https://github.com/fakeyanss/jt808-server-go/assets/34267548/4d0b82aa-1ee8-43f1-b40d-a5932672c93d)
在判断不是分包的情况下,应该要把分包完成标志设置为true吧,否则801消息回复回去检查缓存

**Comment by fakeyanss** [comment]
@supawei 看起来是，你可以提个修复的pr上来，谢谢～

**Comment by fakeyanss** [comment]
已经验证+修复。
thanks to @supawei ~
