### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 2823669007** [fakeyanss/jt808-server-go#17]
ERROR | tcp_server.go:100 > Failed to serve session | error="Fail to process data: Fail to find device cache, phoneNumber=014149487714: device not found" id=111.55.138.96:7091

**Comment by fakeyanss** [comment]
用[v0.3.2](https://github.com/fakeyanss/jt808-server-go/tree/v0.3.2) 或者源码运行。
如果版本对，把报错日志上下文一起发出来看看。
