### ISSUE TITLE
how to using audio and video transmission control of JT1078 protocol with this api.go ?

### ISSUE THREAD

**Issue by anggasetiawanw** [fakeyanss/jt808-server-go#19]

**Comment by fakeyanss** [comment]
实际上，这一部分功能还未完全实现，https://github.com/fakeyanss/jt808-server-go/blob/main/README.md#%E5%A4%9A%E5%AA%92%E4%BD%93%E5%8D%8F%E8%AE%AE 。

最近以来我没太多空闲的时间，并且对于音视频的流传输相关技术还需要深入学习，所以这一部分仍然是WIP状态。

如果你有兴趣，也可以参与这一部分的功能开发。

Actually, this part of the functionality has not been fully implemented yet. You can find more details at https://github.com/fakeyanss/jt808-server-go/blob/main/README.md#%E5%A4%9A%E5%AA%92%E4%BD%93%E5%8D%8F%E8%AE%AE.

Lately, I haven't had much free time, and I still need to dive deeper into the technology related to audio and video streaming. Therefore, this section is still a work in progress (WIP).

If you are interested, you are also welcome to contribute to the development of this part of the functionality.
