### ISSUE TITLE
请问jt1078服务如何对接

### ISSUE THREAD

**Issue by chenfeg** [fakeyanss/jt808-server-go#22]
1078视频服务的直播/点播指令也是通过808连接通道下发到设备，然后设备按指令中的地址端口连接到视频服务上，成功后发送音视频流的

**Comment by fakeyanss** [comment]
See #19
实现1078协议应该在实现完成基础的多媒体协议后，这一部分并没有开始开发。

**Comment by chenfeg** [comment]
谢谢，明白
